import Banner from '@/components/pages/home/banner/Banner';
import DiscountBanner from '@/components/pages/home/banner/DiscountBanner';
import Image from 'next/image';
import StoreBanner from '@/components/pages/home/banner/StoreBanner';
import { getData } from '@/helper/fetchData';
import { isArray } from 'util';
import ProductList from '@/components/ProductList';

export const metadata = {
  title: 'Shofy | Home',
  description: 'Generated by create next app',
};

export default async function Home() {
  const products = await getData('https://dummyjson.com/products');

  return (
    <main className="bg-white">
      <Banner />
      <DiscountBanner />
      <ProductList product={products} />
      <StoreBanner />
    </main>
  );
}
